### ISSUE TITLE
error calling json: invalid character '.' after object key:value pair

### ISSUE THREAD

**Issue by chrisjenx** [kelseyhightower/confd#148]
I get the following error with 0.6.3 (and 0.6.2).
ERROR template: elasticsearch.yml.tmpl:62:11: executing "elasticsearch.yml.tmpl" at <json .>: error calling json: invalid character '.' after object key:value pair

I have the following in my template:

``` golang
discovery.zen.ping.unicast.hosts: [{{range gets "/services/elasticsearch/*"}}
{{$data := json .Value}}"{{$data.IP}}:{{$data.HttpPort}}",
{{end}}]
```

I have no keys set at this point, but I would assume it would never go into the range if there are no keys yet set?

As it seems to be complaining about this: `{{$data := json .Value}}`

TOML for brevity: 

``` toml
keys        = [
  "/services/elasticsearch/"
]
owner       = "elasticsearch"
mode        = "0644"
src         = "elasticsearch.yml.tmpl"
dest        = "/opt/elasticsearch/config/elasticsearch.yml"
```

Am I doing something odd?
