### ISSUE TITLE
Namespace for template resource keys?

### ISSUE THREAD

**Issue by rjocoleman** [kelseyhightower/confd#18]
@kelseyhightower 

Have you considered namespacing watched keys in template resources similar to the global `prefix` option?

Something like an nginx _site_ you may want to use a common template but have a discrete template resource watching separate keys. e.g. 

`example.com.toml`

``` toml
[template]
src   = "example.conf.tmpl"
dest  = "/etc/nginx/sites-enabled/example.com.conf"
owner = "root"
group = "root"
mode  = "0644"
prefix = "site"
keys = [
  "/nginx/examplecom"
]
check_cmd  = "/usr/sbin/nginx -t -c {{ .src }}"
reload_cmd = "/usr/sbin/service nginx restart"
```

`example.net.toml`

``` toml
[template]
src   = "example.conf.tmpl"
dest  = "/etc/nginx/sites-enabled/example.net.conf"
owner = "root"
group = "root"
mode  = "0644"
prefix = "site"
keys = [
  "/nginx/examplenet"
]
check_cmd  = "/usr/sbin/nginx -t -c {{ .src }}"
reload_cmd = "/usr/sbin/service nginx restart"
```

`example.conf.tmpl`

```
server {
    listen 80;
    server_name www.{{ .site_domain }};
    access_log /var/log/nginx/{{ .site_domain }}.access.log;
    error_log /var/log/nginx/{{ .site_domain }}.log;

    location / {
        root   {{ .site_root }};
        index  index.html index.htm;
    }
}
```

``` shell
$ etcdctl set /nginx/examplecom/domain "example.com"
$ etcdctl set /nginx/examplenet/domain "example.net"
$ etcdctl set /nginx/examplecom/root "/var/www/example.com"
$ etcdctl set /nginx/examplenet/root "/var/www/example.net"
```

`example.com.conf`

```
server {
    listen 80;
    server_name www.example.com
    access_log /var/log/nginx/example.com.access.log;
    error_log /var/log/nginx/example.com.log;

    location / {
        root   /var/www/example.com;
        index  index.html index.htm;
    }
}
```

`example.net.conf`

```
server {
    listen 80;
    server_name www.example.net
    access_log /var/log/nginx/example.net.access.log;
    error_log /var/log/nginx/example.net.log;

    location / {
        root   /var/www/example.net;
        index  index.html index.htm;
    }
}
```

Theoretically this would allow for DRY templates. 

I see this as being potential problematic if you wanted to have everything pointed to say `/var/www` and use a common `etcd` key for both sites, but different template (for say logging purposes).
Perhaps the prefix could be set per watch key/dir like so:

`foobar.toml`

``` toml
[template]
src   = "foobar.conf.tmpl"
dest  = "/etc/nginx/sites-enabled/foobar.conf"
owner = "root"
group = "root"
mode  = "0644"
keys = [
 ["/nginx/foobar","site"],
 "/nginx/root"
]
check_cmd  = "/usr/sbin/nginx -t -c {{ .src }}"
reload_cmd = "/usr/sbin/service nginx restart"
```

`example.conf.tmpl`

```
server {
    listen 80;
    server_name www.{{ .site_domain }};
    access_log /var/log/nginx/{{ .site_domain }}.access.log;
    error_log /var/log/nginx/{{ .site_domain }}.log;

    location / {
        root   {{ .nginx_root }};
        index  index.html index.htm;
    }
}
```

``` shell
$ etcdctl set /nginx/foobar/domain "google.com"
$ etcdctl set /nginx/root "/var/www/"
```

`foobar.conf`

```
server {
    listen 80;
    server_name www.google.com
    access_log /var/log/nginx/google.com.access.log;
    error_log /var/log/nginx/google.com.log;

    location / {
        root   /var/www/;
        index  index.html index.htm;
    }
}
```
