### ISSUE TITLE
gets doesn't strip leading /

### ISSUE THREAD

**Issue by olalonde** [kelseyhightower/confd#350]
Some background: I'm trying to make a Docker container completely configurable using just env variables but also have the option to get configuration from an etcd backend if available.

Here's what I have so far:

`bitcoin.toml`
```toml
[template]
src = "bitcoin.conf.tmpl"
dest = "/etc/bitcoin.conf"
owner = "bitcoin"
mode = "0600"
keys = [
  "/rpcport",
  "/rpcuser",
  "/rpcpassword",
]
reload_cmd = "rc-service bitcoind restart"
```

`bitcoin.conf.tmpl`
```tmpl
{{range gets "/*"}}
{{.Key}}="{{.Value}}"
{{end}}
```

```bash
LIVENET_RPCPORT=123
confd -onetime -backend env -prefix livenet
```

Generated `bitcoin.conf`
```ini
/rpcport="123"
```

Two questions:

1) Any way to strip the leading slash `/` to get this result instead?

```ini
rpcport="123"
```

2) I'd rather not manually list all possible keys my configuration can take. For example, I'd like any environment variable `LIVENET_SOMETHING` or etcd key `/livenet/something` to be written to the conf file as `something="value"`. Is that possible or do all possible keys need to be hardcoded in `bitcoin.toml`?
