### ISSUE TITLE
Suggestion: Augeas resource

### ISSUE THREAD

**Issue by raphink** [kelseyhightower/confd#425]
Templates are very useful, but they usually mean you need to maintain the whole configuration file as a template, and update it entirely with each new version of the software.

Augeas allows for a more fine-grained approach of configuration, which could typically be used to map a single parameter to a single change in a config file.

Yesterday, I started a PoC of a tool that would take env variables and generate Augeas code from them: https://github.com/camptocamp/contuner/blob/master/main.go

It seems though that it might be a better idea to add this as a resource type in confd, so that you could write things like:

``` toml
[augeas]
src = "/path/to/augeas/script.tmpl"
keys = [
  "/nginx",
]
reload_cmd = "/usr/sbin/service nginx restart"
```

What think ye? Would you be willing to take such as contribution?
