### ISSUE TITLE
Raw JSON to file

### ISSUE THREAD

**Issue by sgrunt91** [kelseyhightower/confd#535]
Hi,

I'm trying to create config file from Rancher Metadata API. I'm inspiring myself from this project: https://github.com/objectpartners/rancher-container-conf

But I just want directly json of the API to the file. This because the application which will use the generated config file need JSON syntax.

I can have with curl:
```

curl --header 'Accept: application/json' http://rancher-metadata/2015-07-25/self/service/metadata/config/content
{"blabla":{"blublu":{"blibli":[],"bloblo":{"nyark":["firstName","name","birthName"]}}}}
```

But I don't understand what to put in template instead of `getv` to just get raw JSON data (like curl).

This is my `rancher-compose.yml` file, if this could help you to understand me:
```
version: '2'
services:
  app:
    metadata:
      config:
        path: /config/app.conf  
        content:  
          blabla:
            blublu:
              blibli: []
              bloblo:
                nyark:
                - firstName
                - name
                - birthName
    scale: 1
    start_on_create: true

```

I could just use a `curl` container to create a file, but I would benefit of `confd` dynamic update.

Do you understand me ? Is it insane ? :)

Thanks a lot if you try to help me!

Best Regards,
