### ISSUE TITLE
[0.12.0] "Key not found" error with exists pipeline

### ISSUE THREAD

**Issue by jeffjen** [kelseyhightower/confd#585]
Example template and resource:
```
version: "3"
services:
  api:
    env_file:
      - env_api
    image: {{ getv "/swarm/repo" }}/api:{{ getenv "version_api" }}{{ if exists "/swarm/port/api/public" }}
    ports:
      - "{{ getv "/swarm/port/api/public" }}:8080"{{ end }}
    networks:
      - default
```

```
[template]
src = "release.yml.tmpl"
dest = "dist/release.yml"
keys = [
  "/swarm/repo",
  "/swarm/port/api/public"
]
```

Output error log
```
2017-08-11T11:08:29+08:00 - confd[24925]: ERROR 100: Key not found (/devops/swarm/port) [5075]
2017-08-11T11:08:29+08:00 - confd[24925]: FATAL 100: Key not found (/devops/swarm/port) [5075]
```
