### ISSUE TITLE
Rancher backend can't recursively load keys ending in an index of json objects array

### ISSUE THREAD

**Issue by slavniyteo** [kelseyhightower/confd#587]
Hallo, I have some issue with rancher backend. 

**confd versions**: `v0.11.0` and `0.12.0`.

**.toml** file:
```toml
[template]
src = "test.tmpl"
dest = "/test"
keys = [
  "/2016-07-29/self/service/containers",
]
```

**.tmpl** file:
```tmpl
{{getv "/2016-07-29/self/service/containers/0/name"}}
```

**command** (inside docker container started by rancher):
```bash
confd -onetime -backend rancher
```

**Expected behaviour:** file /test contains name of first created container of this service.
```
default-confd-1
```

**Actual behaviour:** 
```
/confd/confd-0.12.0-linux-amd64[12]: FATAL template: test.tmpl:1:2: executing "config.yml.tmpl" at <getv  "/2016-07-29/se...>: error calling getv: key does not exist: /2016-07-29/self/service/containers/0/name
```

---

**Note 1** If I use foolowing toml file, all works fine, but I must specify every container:
```toml
[template]
src = "test.tmpl"
dest = "/test"
keys = [
  "/2016-07-29/self/service/containers/0",
]
```

---

**Note 2** If I use metadata version 2015-07-25, all keys "/2015-07-29/self/service/containers/" are loaded correct because it is array of strings (names of containers), not json objects.
