### ISSUE TITLE
Panic on watched file change

### ISSUE THREAD

**Issue by tymfear** [kelseyhightower/confd#715]
Getting the following error when processing with backend = `file` and `-watch` parameter:
```bash
goroutine 36 [running]:
github.com/kelseyhightower/confd/backends/file.(*Client).watchChanges.func1(0xc4201d43c0, 0xc4202e22a0, 0xc420294180, 0x2b, 0xc4201fa480)
	/go/src/github.com/kelseyhightower/confd/backends/file/client.go:122 +0x1f7
created by github.com/kelseyhightower/confd/backends/file.(*Client).watchChanges
	/go/src/github.com/kelseyhightower/confd/backends/file/client.go:111 +0xb1
```
* myconfig.toml
```toml
[template]
src = "myconfig.conf.tmpl"
dest = "/tmp/myconfig.xml"
keys = [
    "/ips",
]
```
* confd.toml
```toml
backend = "file"
file = ["/etc/confd/ips.yaml"]
```
* myconfig.conf.tmpl
```tmpl
{{ range (split (getv "/ips") ",") -}}
    "{{ . }}"
{{ end }}
```

* ips.yaml
```yaml
ips: '123.321,333.2222.1111,6126786788,123.7'
```

OS: `MacOS Sierra 10.12.6`

STR:
1. Create listed files
2. Execute `confd -watch`
3. Change the *** ips.yaml*** file
