### ISSUE TITLE
Build recursive hierarchical tree is possible?

### ISSUE THREAD

**Issue by 4n70w4** [kelseyhightower/confd#739]
I want to build an arbitrary hierarchical tree. Is it possible to do this?

Example keys:

```
/app/module1/integration1/env1/key1 = value1
/app/module1/integration1/env1/key2 = value2
/app/module2/integration1/env1/key1 = value3
/app/module3/integration2/key1 = value4
/app/module4/key1 = value5
```

I expected build this:

```
app:
  module1:
    integration1:
      env1:
        key1: value1
        key2: value2
  module2:
    integration1:
      env1:
        key1: value3
  module3:
    integration2:
      key1: value4
  module4:
    key1: value5
```
